/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as ModelsModelRouteImport } from './routes/models/$model'
import { Route as CountriesCodeRouteImport } from './routes/countries/$code'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiEntriesRouteImport } from './routes/api/entries'
import { Route as ApiModelsModelRouteImport } from './routes/api/models/$model'
import { Route as ApiEntriesSearchRouteImport } from './routes/api/entries/search'
import { Route as ApiEntriesHandleRouteImport } from './routes/api/entries/$handle'
import { Route as ApiCountriesStatsRouteImport } from './routes/api/countries/stats'
import { Route as ApiCountriesCodeRouteImport } from './routes/api/countries/$code'
import { Route as ApiEntriesHandleStandingRouteImport } from './routes/api/entries/$handle/standing'
import { Route as ApiEntriesHandleRefreshRouteImport } from './routes/api/entries/$handle/refresh'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelRoute = ModelsModelRouteImport.update({
  id: '/models/$model',
  path: '/models/$model',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCodeRoute = CountriesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => CountriesRoute,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntriesRoute = ApiEntriesRouteImport.update({
  id: '/api/entries',
  path: '/api/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsModelRoute = ApiModelsModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => ApiModelsRoute,
} as any)
const ApiEntriesSearchRoute = ApiEntriesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiEntriesRoute,
} as any)
const ApiEntriesHandleRoute = ApiEntriesHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => ApiEntriesRoute,
} as any)
const ApiCountriesStatsRoute = ApiCountriesStatsRouteImport.update({
  id: '/api/countries/stats',
  path: '/api/countries/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesCodeRoute = ApiCountriesCodeRouteImport.update({
  id: '/api/countries/$code',
  path: '/api/countries/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntriesHandleStandingRoute =
  ApiEntriesHandleStandingRouteImport.update({
    id: '/standing',
    path: '/standing',
    getParentRoute: () => ApiEntriesHandleRoute,
  } as any)
const ApiEntriesHandleRefreshRoute = ApiEntriesHandleRefreshRouteImport.update({
  id: '/refresh',
  path: '/refresh',
  getParentRoute: () => ApiEntriesHandleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countries': typeof CountriesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/entries': typeof ApiEntriesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/models/$model': typeof ModelsModelRoute
  '/models/': typeof ModelsIndexRoute
  '/api/countries/$code': typeof ApiCountriesCodeRoute
  '/api/countries/stats': typeof ApiCountriesStatsRoute
  '/api/entries/$handle': typeof ApiEntriesHandleRouteWithChildren
  '/api/entries/search': typeof ApiEntriesSearchRoute
  '/api/models/$model': typeof ApiModelsModelRoute
  '/api/entries/$handle/refresh': typeof ApiEntriesHandleRefreshRoute
  '/api/entries/$handle/standing': typeof ApiEntriesHandleStandingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countries': typeof CountriesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/entries': typeof ApiEntriesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/models/$model': typeof ModelsModelRoute
  '/models': typeof ModelsIndexRoute
  '/api/countries/$code': typeof ApiCountriesCodeRoute
  '/api/countries/stats': typeof ApiCountriesStatsRoute
  '/api/entries/$handle': typeof ApiEntriesHandleRouteWithChildren
  '/api/entries/search': typeof ApiEntriesSearchRoute
  '/api/models/$model': typeof ApiModelsModelRoute
  '/api/entries/$handle/refresh': typeof ApiEntriesHandleRefreshRoute
  '/api/entries/$handle/standing': typeof ApiEntriesHandleStandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countries': typeof CountriesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/entries': typeof ApiEntriesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/models/$model': typeof ModelsModelRoute
  '/models/': typeof ModelsIndexRoute
  '/api/countries/$code': typeof ApiCountriesCodeRoute
  '/api/countries/stats': typeof ApiCountriesStatsRoute
  '/api/entries/$handle': typeof ApiEntriesHandleRouteWithChildren
  '/api/entries/search': typeof ApiEntriesSearchRoute
  '/api/models/$model': typeof ApiModelsModelRoute
  '/api/entries/$handle/refresh': typeof ApiEntriesHandleRefreshRoute
  '/api/entries/$handle/standing': typeof ApiEntriesHandleStandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/countries'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/entries'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/models'
    | '/api/stats'
    | '/countries/$code'
    | '/models/$model'
    | '/models/'
    | '/api/countries/$code'
    | '/api/countries/stats'
    | '/api/entries/$handle'
    | '/api/entries/search'
    | '/api/models/$model'
    | '/api/entries/$handle/refresh'
    | '/api/entries/$handle/standing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/countries'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/entries'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/models'
    | '/api/stats'
    | '/countries/$code'
    | '/models/$model'
    | '/models'
    | '/api/countries/$code'
    | '/api/countries/stats'
    | '/api/entries/$handle'
    | '/api/entries/search'
    | '/api/models/$model'
    | '/api/entries/$handle/refresh'
    | '/api/entries/$handle/standing'
  id:
    | '__root__'
    | '/'
    | '/countries'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/entries'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/models'
    | '/api/stats'
    | '/countries/$code'
    | '/models/$model'
    | '/models/'
    | '/api/countries/$code'
    | '/api/countries/stats'
    | '/api/entries/$handle'
    | '/api/entries/search'
    | '/api/models/$model'
    | '/api/entries/$handle/refresh'
    | '/api/entries/$handle/standing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountriesRoute: typeof CountriesRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiEntriesRoute: typeof ApiEntriesRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiModelsRoute: typeof ApiModelsRouteWithChildren
  ApiStatsRoute: typeof ApiStatsRoute
  ModelsModelRoute: typeof ModelsModelRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  ApiCountriesCodeRoute: typeof ApiCountriesCodeRoute
  ApiCountriesStatsRoute: typeof ApiCountriesStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$model': {
      id: '/models/$model'
      path: '/models/$model'
      fullPath: '/models/$model'
      preLoaderRoute: typeof ModelsModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$code': {
      id: '/countries/$code'
      path: '/$code'
      fullPath: '/countries/$code'
      preLoaderRoute: typeof CountriesCodeRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entries': {
      id: '/api/entries'
      path: '/api/entries'
      fullPath: '/api/entries'
      preLoaderRoute: typeof ApiEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models/$model': {
      id: '/api/models/$model'
      path: '/$model'
      fullPath: '/api/models/$model'
      preLoaderRoute: typeof ApiModelsModelRouteImport
      parentRoute: typeof ApiModelsRoute
    }
    '/api/entries/search': {
      id: '/api/entries/search'
      path: '/search'
      fullPath: '/api/entries/search'
      preLoaderRoute: typeof ApiEntriesSearchRouteImport
      parentRoute: typeof ApiEntriesRoute
    }
    '/api/entries/$handle': {
      id: '/api/entries/$handle'
      path: '/$handle'
      fullPath: '/api/entries/$handle'
      preLoaderRoute: typeof ApiEntriesHandleRouteImport
      parentRoute: typeof ApiEntriesRoute
    }
    '/api/countries/stats': {
      id: '/api/countries/stats'
      path: '/api/countries/stats'
      fullPath: '/api/countries/stats'
      preLoaderRoute: typeof ApiCountriesStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries/$code': {
      id: '/api/countries/$code'
      path: '/api/countries/$code'
      fullPath: '/api/countries/$code'
      preLoaderRoute: typeof ApiCountriesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entries/$handle/standing': {
      id: '/api/entries/$handle/standing'
      path: '/standing'
      fullPath: '/api/entries/$handle/standing'
      preLoaderRoute: typeof ApiEntriesHandleStandingRouteImport
      parentRoute: typeof ApiEntriesHandleRoute
    }
    '/api/entries/$handle/refresh': {
      id: '/api/entries/$handle/refresh'
      path: '/refresh'
      fullPath: '/api/entries/$handle/refresh'
      preLoaderRoute: typeof ApiEntriesHandleRefreshRouteImport
      parentRoute: typeof ApiEntriesHandleRoute
    }
  }
}

interface CountriesRouteChildren {
  CountriesCodeRoute: typeof CountriesCodeRoute
}

const CountriesRouteChildren: CountriesRouteChildren = {
  CountriesCodeRoute: CountriesCodeRoute,
}

const CountriesRouteWithChildren = CountriesRoute._addFileChildren(
  CountriesRouteChildren,
)

interface ApiEntriesHandleRouteChildren {
  ApiEntriesHandleRefreshRoute: typeof ApiEntriesHandleRefreshRoute
  ApiEntriesHandleStandingRoute: typeof ApiEntriesHandleStandingRoute
}

const ApiEntriesHandleRouteChildren: ApiEntriesHandleRouteChildren = {
  ApiEntriesHandleRefreshRoute: ApiEntriesHandleRefreshRoute,
  ApiEntriesHandleStandingRoute: ApiEntriesHandleStandingRoute,
}

const ApiEntriesHandleRouteWithChildren =
  ApiEntriesHandleRoute._addFileChildren(ApiEntriesHandleRouteChildren)

interface ApiEntriesRouteChildren {
  ApiEntriesHandleRoute: typeof ApiEntriesHandleRouteWithChildren
  ApiEntriesSearchRoute: typeof ApiEntriesSearchRoute
}

const ApiEntriesRouteChildren: ApiEntriesRouteChildren = {
  ApiEntriesHandleRoute: ApiEntriesHandleRouteWithChildren,
  ApiEntriesSearchRoute: ApiEntriesSearchRoute,
}

const ApiEntriesRouteWithChildren = ApiEntriesRoute._addFileChildren(
  ApiEntriesRouteChildren,
)

interface ApiModelsRouteChildren {
  ApiModelsModelRoute: typeof ApiModelsModelRoute
}

const ApiModelsRouteChildren: ApiModelsRouteChildren = {
  ApiModelsModelRoute: ApiModelsModelRoute,
}

const ApiModelsRouteWithChildren = ApiModelsRoute._addFileChildren(
  ApiModelsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountriesRoute: CountriesRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiEntriesRoute: ApiEntriesRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiModelsRoute: ApiModelsRouteWithChildren,
  ApiStatsRoute: ApiStatsRoute,
  ModelsModelRoute: ModelsModelRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  ApiCountriesCodeRoute: ApiCountriesCodeRoute,
  ApiCountriesStatsRoute: ApiCountriesStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
